---
title: "Academic Paper"
format: html
editor: visual
---

## Literature Review

**Introduction**

Rural Aboriginal communities in Australia face many disadvantages, from disproportionate access to health, education, and transport services to the lasting impacts of European colonization, which hindered the intergenerational transference of language and knowledge, and the legacy of former governmental policies designed to socially isolate Aboriginal communities and forbid their cultural practices.(,)  The combination of these challenges faced by rural Aboriginal communities in recent decades further exacerbates the effects of perhaps the most pressing challenge of all: climate change.

Global warming is predicted to lead to increased incidence of extreme weather events in Australia, such as droughts, floods, and bushfires, which will have their most adverse impact on Aboriginal Australians. In 2019 and 2020, catastrophic bushfires ravaged homelands of Australian Indigenous peoples which have been colonized by European nations in recent centuries. This colonization subsequently suppressed Indigenous landscape management, which has profound social and environmental impacts in the wake of catastrophic climate events like bushfires. In these communities, where environment and people have been intertwined for over 60,000 years, the tasks of protecting cultural practices and protecting the planet cannot be separated. 

Because Aboriginal peoples are uniquely positioned at the frontlines of the climate crisis, it is crucial to understand the ways in which Indigenous communities adapt to climate change and impact of climate events on individuals and communities. This research project will be participatory action research that will seek to understand specific climate vulnerabilities and adaptive capacities of one or more remote Aboriginal communities while answering the following questions: "What is the impact of climate catastrophes such as bushfires and the loss of marine ecosystems on remote Aboriginal communities in New South Wales? Furthermore, how can these communities preserve their traditions and cultural practices while adapting to climate risks and utilize these traditions as a means for protection from said risks?" In the review below, I will examine literature related to these questions that draws from schools of thought on: 1) cultural ecology, 2) collectivism and individualism, and 3) decolonizing science and policy.

**Cultural Ecology**

Scholars examine cultural ecology as a facet of sociology focused on human adaptation to social and physical environments. In the context of climate change, according to Baer, the cultural-ecological perspective "draws attention to the ways people collectively respond and use their sociocultural system" to cope with climatic threats. A cultural-ecological perspective supports the idea that anthropologists should enter into a serious dialogue with Aboriginal and Indigenous peoples in order to understand their commitment to place and experience witnessing ecosystem shifts. Because Aboriginal communities risk becoming internal climate refugees as a means of adaptation to their physical environment in the wake of the recent increase in deadly bushfires, cultural ecology evidences the need for a viable Aboriginal-environmentalist alliance in order to understand local responses to and observations about these bushfires.

In agreement with Baer's observations on the need for cultural ecology, Green maintains that "local observations have been recognised by non-Indigenous scientists as a vital source of environmental data where few historic records exist." Documenting Indigenous environmental knowledge allows for the creation of community-owned knowledge databases and the passage of knowledge to younger generations, which builds capacity within the community to manage traditional knowledge. 

Additionally, some scholars believe there is a need for a nationwide approach to reduce greenhouse gas emissions in Australia that is flexible enough to "enable local responses to local conditions". However, through the lens of cultural ecology, a school of thought which overwhelmingly supports a dialogue with Indigenous communities, further studies would be required before the implementation of a national climate response that risks generalizing about Aboriginal communities. Localized, cultural-ecological, ethnohistorical records have the potential to "contribute substantially" to an understanding of Aboriginal cultural burning practices, contemporary natural resource management, and other climate adaptation-related topics.

**Collectivism and Individualism**

Matthews contends that capitalism, colonialism, and climate change reflect the dominance of Western individualistic philosophies that promote the exploitation of the environment, whereas Indigenous collectivist philosophies focus on deep relationships with the environment and creation of millenias-old knowledge systems. Through this collectivist view, loss of land has meant intergenerational trauma in Aboriginal communities and a feeling of intrinsic connection between climate justice and Aboriginal justice. 

The collectivist school of thought emphasizes the mutually beneficial reciprocity between Aboriginals and the world around them, a much different relationship than the land management paradigm in place in Australia today. These reciprocal relationships, in which communities depend on the environment economically, culturally, and for health reasons, bring people together in response to climate change. Co-management and Indigenous ranger programs, environmental research programs which engage Indigenous Australians in research that combines contemporary scientific and traditional ecological knowledge, can foster this reciprocity. Establishing a climate of reciprocal reliability between Indigenous peoples, the environment, and contemporary scientists and government agencies is critical for the establishment of shared knowledge.

**Decolonizing Science and Policy**

Colonized ideas of science perpetuate a nature-culture binary that promotes an idea of "wilderness" and hinders Indigenous practices like cultural burning. Furthermore, the political sphere remains colonized, with Aboriginal Australians lacking a voice in Parliament. Whyte argues that responding to colonialism and its effects rather than catering to non-Indigenous resource management interests leads to an effective response to climate change, saying: "While Indigenous knowledges obviously have useful information about the nature of ecological changes, it is perhaps more interesting to explore how renewing Indigenous knowledges serves the motivation of people and communities to address climate change." Neale echoes these statements, suggesting that Indigenous communities carry the unreasonable burden of the colonial idea of solving climate change and washing away the "ills of modernity".

This problematic view of traditionalism is used to govern Aboriginal peoples and serve the interests of non-Indigenous peoples, reducing Aboriginal knowledge to only its supplemental value and leaving the "injustice of settler-Indigenous relations" untouched. To decolonize science and policy, it is important to reimagine the role of Western science as a leg to elevate Indigenous knowledge and stewardship rather than a vessel in which to integrate Indigenous knowledge. Furthermore, decolonizing policy involves shifting power structures to recognize Indigenous people as rights-holders in environmental management and ensuring Indigenous governance structures that safeguard the Indigenous right to challenge the onto-epistemological foundations of environmental management.

**Gaps and Contribution**

The existing research shows that a large body of participatory Indigenous climate knowledge, especially in New South Wales, has not yet been recorded. Furthermore, there are very few accounts of current Aboriginal peoples and their burning practices that include Aboriginal perspectives and are not "simplistic and stereotyped". There is a need for more up-to-date, localized research on southeastern Australia that shows the differences and/or similarities in Indigenous communities and creates context to which existing, generalized findings on Indigenous Australians can be applied.

Thus, my research will seek to discover opportunities to enhance environmental management using equitable governance structures and processes, decolonize the traditionalist view of Aboriginal knowledge in southeast Australia, and record diverse perspectives on contemporary knowledge, cultural practice, and tradition, creating a foundation for future adaptation within these communities and helping to guide and inform governmental policies in regions with large Indigenous populations.

**Works Cited**

Atkinson, Amos, and Cristina Montiel-Molina. "Reconnecting fire culture of Aboriginal communities with contemporary Wildfire Risk Management." Fire, vol. 6, no. 8, 2023, p. 296, <https://doi.org/10.3390/fire6080296>.

Bay, Line K., et al. "Management approaches to conserve Australia's marine ecosystem under climate change." Science, vol. 381, no. 6658, 2023, pp. 631--636, <https://doi.org/10.1126/science.adi3023>.

Burgess, Christopher P, et al. "Healthy Country, healthy people: The relationship between indigenous health status and 'Caring for country.'" Medical Journal of Australia, vol. 190, no. 10, 2009, pp. 567--572, <https://doi.org/10.5694/j.1326-5377.2009.tb02566.x>.

Cahir, Fred, et al. "winda lingo parugoneit1or why set the bush \[on\] fire? fire and victorian aboriginal people on the Colonial Frontier." Australian Historical Studies, vol. 47, no. 2, 2016, pp. 225--240, https://doi.org/10.1080/1031461x.2016.1156137.

"Cultural Ecology." Encyclopædia Britannica, Encyclopædia Britannica, inc., www.britannica.com/topic/cultural-ecology. Accessed 31 Oct. 2023.

Daniell, Katherine A., et al. "Breaking down the 'one-size-fits-all' approach to rural and regional policy: Enhancing policy initiatives through multi-level governance." Multi-Level Governance: Conceptual Challenges and Case Studies from Australia, 2017, pp. 403--428, <https://doi.org/10.22459/mg.11.2017.17>.

Dickson‐Hoyle, Sarah, et al. "Walking on two legs: A pathway of indigenous restoration and reconciliation in fire‐adapted landscapes." Restoration Ecology, vol. 30, no. 4, 2021, <https://doi.org/10.1111/rec.13566>.

Fletcher, Michael-Shawn, et al. "Catastrophic bushfires, indigenous fire knowledge and reframing science in Southeast Australia." Fire, vol. 4, no. 3, 2021, p. 61, https://doi.org/10.3390/fire4030061.

Green, Donna, et al. "Indigenous Australians' knowledge of weather and climate." Climatic Change, vol. 100, no. 2, 2010, pp. 337--354, <https://doi.org/10.1007/s10584-010-9803-z>.

Matthews, Veronica, et al. "Justice, culture, and relationships: Australian Indigenous Prescription for Planetary Health." Science, vol. 381, no. 6658, 2023, pp. 636--641, https://doi.org/10.1126/science.adh9949.

Muller, Samantha, et al. "Indigenous sovereignties: Relational ontologies and environmental management." Geographical Research, vol. 57, no. 4, 2019, pp. 399--410, <https://doi.org/10.1111/1745-5871.12362>.

Neale, Timothy. "What tradition affords." Current Anthropology, vol. 64, no. 1, 2023, pp. 72--103, <https://doi.org/10.1086/722533>.

Walker, Joanne. "Rural health inequities and the impact of climate change." Australian Journal of Rural Health, vol. 27, no. 6, 2019, pp. 583--584, https://doi.org/10.1111/ajr.12595. 

Weir, John, and Derek Scasta. "The (re)emergence of Aboriginal women and cultural burning in New South Wales, Australia." Global Application of Prescribed Fire, 2022, <https://doi.org/10.1071/9781486312498>.

Whyte, Kyle. "Indigenous Climate Change Studies: Indigenizing Futures, decolonizing the anthropocene." English Language Notes, vol. 55, no. 1--2, 2017, pp. 153--162, https://doi.org/10.1215/00138282-55.1-2.153.

[HOME](https://sophieholtzman.github.io/mywebsite/index.html)
