---
title: "Newswriting"
format: html
editor: visual
---

## News Story

**In Ward 2, Hobbyist Beekeepers Are Abundant - And It Could Be A Problem**

**By Oliver Grover and Sophie Holtzman**

**Introduction**

DC's second ward is maybe best known for its large population of commuting workers and office buildings, but it's easy to overlook perhaps the hardest working residents of those offices: the bees. Ward 2 is home to dozens of beekeepers and their colonies spread throughout office buildings in the ward, high above the heads of the often unknowing residents on the streets down below. If you've ever taken a stroll through the ward, the chances are you've walked past these colonies. 

DC is home to a bustling community of hobby beekeepers, with beekeeping being an opportunity available for anyone with a permit. At first glance beekeeping in the district seemed to be an accessible way for residents from all backgrounds to join in on an environmental cause. After all, how often have you seen online posts and videos stressing the importance of saving the bees? But as we delved into DC's beekeeping scene we discovered that while beekeeping is an accessible hobby that allows all sorts of city residents to get involved with the environment, it turns out honey bee populations may not be struggling quite as much as the average person may believe, and that beekeeping's accessibility may in fact be hurting bee populations more than it's helping. 

**DC Beekeeping**

Beekeeping as a hobby has been legalized in DC since 2014 due to [The Sustainable Urban Agriculture Apiculture Act](https://doee.dc.gov/service/beekeeping-district), but the history of beekeeping in the city goes back far further than that.

"They've been beekeeping on roofs for centuries in DC," Kevin Platte, a hobbyist beekeeper in Ward 2, said in an interview. "Since the early 1900s." 

We joined Platte for an interview during one of his monthly pop-up sales in the lobby of The Lion Building, an office building which is home to not just his colonies, but the Embassy of Vietnam along with other companies leasing space. As we talked with Platte, other residents of the offices walked by and expressed their surprise at the fact that the building was home to beehives, highlighting just how unaware many residents are of the presence of bees in the ward. 

While a city like DC may not seem well poised to support beekeeping, the city's resources actually allow the bee populations to flourish. According to Platte, the presence of Rock Creek Park as well as the numerous trees lining the streets provide bees with plenty of resources. Additionally, urban settings such as DC provide unique advantages to bee populations.

"A lot of people say the best honey is urban honey," Sean Kennedy, a beekeeper with one of the largest apiaries in the city, said in an interview. "Because generally people aren't using pesticides here, as opposed to rural environments." 

Urban beekeepers also generally don't need to worry about predators such as bears, and in elevated environments such as Ward 2's office buildings mice and raccoons are less of a concern. But many hobbyist beekeepers in the city need to worry about a far more dangerous predator than bears: People. 

"In the rural areas they've got wide open space, so they've got to watch for bears. They'll literally come in and tear down and push it over," Platte said. "Here in the city they'll maybe just spray some raid in your hives and kill them off. My hives have been pushed over. You know, people walking by at night. It doesn't break anything, it just kills most of the bees cause they're exposed to the cold."

**Beekeeping As A Hobby**

While beekeeping in a city like DC provides unique advantages and challenges, it also provides a large population of potential hobbyist beekeepers. While commercial beekeepers keep "literally hundreds and hundreds of hives stacked on top of each other," according to Platte, hobbyist beekeepers keep their operations much smaller. And in DC, essentially anyone can be a beekeeper.

"DC Beekeeping Alliance was something that hobby beekeepers lobbied for in order to make it legal, and really by right you can have bees as long as you can keep them 15 feet away from a neighbor's property," Kennedy said.

Both Kennedy and Platte estimated the startup costs for a new beekeeper to be around four to five hundred dollars, on top of the costs for education. However, Platte, an instructor of classes held to train aspiring beekeepers, says that they offer scholarships to keep this education affordable. 

"We provide scholarships for people who are underserved in the area. We give out scholarships for folks who are in areas like in Ward 4, 5, 6, that are underserved in general. You know, in those communities that are ignored." 

With relatively low startup costs and few restrictions on who is able to be a beekeeper, it's a hobby that not only allows residents to participate in nature, but potentially earn some money while doing it. Platte says that in months where he sells all of his product, he can make upwards of a few thousand dollars. But while beekeeping in the city is accessible to residents of all backgrounds, Platte shared some concerns with us that the abundance of beekeepers in the city may be becoming a problem.

**Save The Bees - But Which Ones?**

For many, saving the bees is a familiar concept. Since the early 2000s certain types of bees have found themselves endangered due to colony collapse. Saving the bees is a worthwhile endeavor, as the consequences of complete population collapse would be devastating. 

"Twenty years ago we had colony collapse disorder. It's not very prevalent now, but there was a very real fear that bees were going to sort of die out in the US," Kennedy said. "And the problem is we brought in an invasive species, and we built up an agricultural system dependent on them. And if that pollinator were to go away, it would be tragic." 

Bees are an important pollinator of many American crops. According to Kennedy, if honey bees were to stop existing, crops such as almonds, apples, and other fruits would be at a loss for pollination. But while saving the bees is important, it's also important to know which bees need saving - and what they need saving from.

"We learned a lot of lessons from that situation in the 90s. There's no longer a problem with it, because we learned how to deal with the pest that's the primary carrier of it. If they do collapse, you didn't do something correctly as a beekeeper." 

Instead, the biggest threat to native bee populations are other bees. The types of honey bees beekeepers tend to work with are technically an invasive species, coming from Europe dating all the way back to the colonists. But in an environment like DC, these invasive honey bees and the native populations of bees in the city - [approximately 130 different species](https://doee.dc.gov/sites/default/files/dc/sites/ddoe/service_content/attachments/Final%20P3.pdf)- are all competing for the same resources. 

"In urban settings if you've read recently, is the density of beekeeping too intense? Too many bees!" Platte said. "Which is then why is that a problem? Because they're taking resources from the native bees."

Unfortunately, trying to address the issue of having too many beekeepers is a complex issue. After all, it was the hobbyist beekeepers themselves who lobbied for legalizing beekeeping in the city. 

"We are talking about that. How do you put a limit on the number of beekeepers?" Platte pondered during our interview. "How do you do that?" 

One potential answer Platte offered up was the expansion of pollinator friendly gardens in the city. Alongside his apiary Platte is the manager of the West End Community Garden, a local garden which is friendly to pollinators such as native bees.

"People are saying 'We need beekeepers!'. No, we need gardens. We have so many bees here now, so many beekeepers and beehives, now we're encouraging people to plant pollinator-friendly gardens to support the native bees." 

Another answer to protecting DC bee populations is to be more mindful of how you treat wild bees. Kennedy urges people to rescue bees rather than exterminate them.
